"""message

Revision ID: fb1ca5a95668
Revises: 90637c438e97
Create Date: 2025-06-22 14:43:33.180708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb1ca5a95668'
down_revision = '90637c438e97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
